arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - en
  - tr
output-dir: lib/core/localization
use-deferred-loading: false
untranslated-messages-file: lib/core/localization/untranslated_messages.txt
