name: hand_speak
description: "İşaret Dili Çeviri ve Öğrenme Uygulaması"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase - Latest compatible versions
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_app_check: ^0.3.1
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3
  
  # UI and Navigation
  flutter_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.0
  go_router: ^13.0.0
  
  # Video and Media
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  url_launcher: ^6.2.4
  youtube_player_flutter: ^9.1.1
  video_player: ^2.8.2
  
  # Authentication and Social Login
  google_sign_in: ^6.2.1
  
  # UI Components
  lottie: ^3.0.0
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  confetti: ^0.7.0
  webview_flutter: ^4.7.0
  
  # Storage and Data
  shared_preferences: ^2.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # Utilities
  permission_handler: ^11.2.0
  intl: ^0.19.0
  equatable: ^2.0.5
  uuid: ^4.3.3
  connectivity_plus: ^5.0.2
  logger: ^2.0.2
  
  # Maps and Location
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.1.0
  
  # ML Kit for translations
  google_mlkit_translation: ^0.13.0
  google_mlkit_pose_detection: ^0.14.0
  google_mlkit_commons: ^0.11.0
  
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.1.0
  qr_flutter: ^4.1.0
  crypto: ^3.0.6
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/tr.png
    - assets/images/en.png
    - assets/lottie/
    - assets/translations/
    
  # Fontu düzgün belirtelim ama dosyalar yoksa yorum satırına alalım
  # fonts:
  #  - family: Poppins
  #    fonts:
  #      - asset: assets/fonts/Poppins-Regular.ttf
  #      - asset: assets/fonts/Poppins-Medium.ttf
  #        weight: 500
  #      - asset: assets/fonts/Poppins-SemiBold.ttf
  #        weight: 600
  #      - asset: assets/fonts/Poppins-Bold.ttf
  #        weight: 700
