// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlKcha3p9rGzU21MI6Pe1DedrCvGJRSAM',
    appId: '1:231396145380:web:2182b89acc956c6fa254f1',
    messagingSenderId: '231396145380',
    projectId: 'handspeak-ace26',
    authDomain: 'handspeak-ace26.firebaseapp.com',
    storageBucket: 'handspeak-ace26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlKcha3p9rGzU21MI6Pe1DedrCvGJRSAM',
    appId: '1:231396145380:android:2182b89acc956c6fa254f1',
    messagingSenderId: '231396145380',
    projectId: 'handspeak-ace26',
    storageBucket: 'handspeak-ace26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlKcha3p9rGzU21MI6Pe1DedrCvGJRSAM',
    appId: '1:231396145380:ios:2182b89acc956c6fa254f1',
    messagingSenderId: '231396145380',
    projectId: 'handspeak-ace26',
    storageBucket: 'handspeak-ace26.firebasestorage.app',
    iosBundleId: 'com.company.Hand_Speak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlKcha3p9rGzU21MI6Pe1DedrCvGJRSAM',
    appId: '1:231396145380:macos:2182b89acc956c6fa254f1',
    messagingSenderId: '231396145380',
    projectId: 'handspeak-ace26',
    storageBucket: 'handspeak-ace26.firebasestorage.app',
    iosBundleId: 'com.company.Hand_Speak',
  );
}
